### ISSUE TITLE
Presentation links incomplete

### ISSUE THREAD

**Issue by bawjensen** [WheatonWHALE/comp401#1]
To link directly to a file in a repo, a '/blob/&lt;branch-name&gt;/' path segment is required before the actual filepath/filename.

For example:
[https://github.com/bawjensen/comp401/blob/master/presentation1.md](https://github.com/bawjensen/comp401/blob/master/presentation1.md)

Instead of 
[https://github.com/bawjensen/comp401/presentation1.md](https://github.com/bawjensen/comp401/presentation1.md)

**Comment by tarmstro** [comment]
So it is! Thanks!
